#pragma once
#include "common.h"
#include <windows.h>

namespace lng
{

	enum LANG
	{
		LANG_RU,
		LANG_EN,
		LANG_MAXID
	};

	enum StringId
	{
		LS_NONE,
		LS_APP_EXCEPTION_TITLE,
		LS_APP_RUNNED_CAPTION,
		LS_FILE_OPEN_FAIL,
		LS_FILE_INVALID,
		LS_HOTKEY_MISSED,
		LS_HOTKEY_THREAD_CREATE_FAIL,
		LS_HOTKEY_DUPLICATE,
		LS_HOTKEY_REGISTER_FAIL,
		LS_MODULEFILE_NAME_FAIL,
		LS_TRAY_REGISTERCLASS_FAIL,
		LS_TRAY_CREATEWND_FAIL,
		LS_TRAY_LOADMENU_FAIL,
		LS_CONFIG_LASTACTION,
		LS_CONFIG_KEY_MISSED,
		LS_CONFIG_KEY_ISNTARRAY,
		LS_CONFIG_LOAD_FAIL,
		LS_CONFIG_HOTKEYS_LOAD_FAIL,
		LS_CONFIG_BUILDS_LOADED,
		LS_CONFIG_BUILDS_FIND_FAIL,
		LS_CONFIG_BUILDS_ERROR_FILE,
		LS_CONFIG_BUILD_NAME_LONG,
		LS_CONFIG_BUILD_RACE_EMPTY,
		LS_CONFIG_BUILD_TIME_INVALID,
		LS_CONFIG_BUILD_STEP,
		LS_CONFIG_BUILD_STEP2,
		LS_CONFIG_BUILD_STEP3,
		LS_CONFIG_WAITTYPE_INVALID,
		LS_CONFIG_WAITTYPE_EXCEPTION,
		LS_CONFIG_ALIGN_INVALID,
		LS_CONFIG_RACE_INVALID,
		LS_CONFIG_ACTION_NAME_LONG,
		LS_CONFIG_RESOLUTION_TOOSMALL,
		LS_CONFIG_RESOLUTION_FRAME_MISSED,
		LS_CONFIG_FONT_NAMELONG,
		LS_CONFIG_GLOBAL_FONT_NOTFOUND,
		LS_CONFIG_GLOBAL_HOTKEY_INVALID,
		LS_CONFIG_GLOBAL_PANELS_BO_MISSED,
		LS_CONFIG_GLOBAL_PANELS_TIPS_MISSED,
		LS_CONFIG_GLOBAL_PANELS_COLOR_INVALID,
		LS_AUDIO_FAIL,
		LS_GAME_RUNNED,
		LS_GAME_OFF,
		LS_OVERLAY_FAIL,
		LS_OVERLAY_MANYERRORS,
		LS_OVERLAY_FINDWND_FAIL,
		LS_OVERLAY_DEVICE_NULL,
		LS_OVERLAY_LINE_CREATE_FAIL,
		LS_OVERLAY_SPRITE_CREATE_FAIL,
		LS_OVERLAY_FONT_CREATE_FAIL,
		LS_OVERLAY_OBJECT_CREATE_FAIL,
		LS_OVERLAY_DEVICE_CREATE_FAIL,
		LS_OVERLAY_TARGETWND_EMPTY,
		LS_OVERLAY_CLASS_REGISTER_FAIL,
		LS_OVERLAY_WND_CREATE_FAIL,


		LS_SOUND_MISSED,
		LS_SOUND_FILE_OPEN_FAIL,
		LS_SOUND_SOURCE_OPEN_FAIL,
		LS_SOUND_SOURCE_CREATE_FAIL,
		LS_SOUND_XAUDIO2_CREATE_FAIL,
		LS_SOUND_XAUDIO2_MASTERVOICE_CREATE_FAIL,
		LS_FONT_SIZE_INVALID,
		LS_FONT_LOAD_FAIL,

		LS_MSG_MUTE,
		LS_MSG_DEBUG,
		LS_MSG_SETTINGS_INVALID,
		LS_MSG_RESOLUTION_UND,
		LS_MSG_HOTKEY_MISSED,
		LS_MSG_BUILD_NULL,

		LS_DEBUG_INFO,
		LS_MAXID
	};

	#define STRING_TABLE std::map<WORD, LPCSTR>
	#define LANGUAGE_ID_RUS 0x419
	#define APP_NAME L"SC2Mentat"
	#define APP_NAME_ANSI "SC2Mentat"

	void initLocale();
	LPCSTR string(StringId id);
	void localizeMenu(HMENU hMenu);
	void localizeDialog(HWND hWnd, WORD dlgId);
}
